language: ruby
dist: xenial
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
rvm:
  - 2.5
cache: bundler
addons:
  snaps:
    - jq
    - yq
before_install:
  - gem update --system
  - gem install bundler
  - sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
  -
  - pip install yq
script:
  - make clean all publish
deploy:
  skip_cleanup: true
  provider: script
  script: >-
    COMMIT_AUTHOR_EMAIL=`yq -r .relaton.collection.name metanorma.yml`
    bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/deploy-to-gh-pages.sh | bash
  on:
    branch: master
